### PR TITLE
Gradle 2.2.3 -> 2.3.0

### PR DESCRIPTION
**Pull request by andyklimczak**
Build tools 24.0.3 -> 25.0.0

### CODE REVIEW

**Comment by Floens** [comment]
`compileSdkVersion` should be upgraded to 25 too. Check if there are any breaking API changes.

**Comment by andyklimczak** [comment]
api changes: https://developer.android.com/sdk/api_diff/25/changes.html

Will research and test more tonight

**Comment by andyklimczak** [comment]
updated and surface tests passed (posting, replying, saving images, gallery, changing save location)

don't feel like this PR is a priority. the only reason I'm aware of gradle updates is because android studio throws popups at me

**Comment by Floens** [comment]
lgtm, thanks for the testing!

**Pull request merged**
