### PR TITLE
Album download to use saveOriginalFilename preference

### PR DESCRIPTION
**Pull request by andyklimczak**
Added check for album download to decide which name to use when saving
the file.
Brought up in issue #155

### CODE REVIEW

**Comment by Floens** [comment]
The reason that album downloads always use the name 4chan provides is because this way the downloader can skip over existing images reliably. If you use the other name and when there are duplicate file names the second one wouldn't be downloaden. I can solve this by doing some md5 checking. But that's the reason why I didn't do this.

**Comment by RubarbKid** [comment]
You could get around the problem by having a filename map.  Each entry in the map would contain the 4chan assigned name and the associated "original" filename.  I use the quotes because if you had 16 "mycat.jpg" files, you'd be able to rename the redundant files to "mycat+2.jpg" and still keep the essence of the original filename...

**Comment by RubarbKid** [comment]
A bit more overhead than a simple file exists check, but much much faster than an md5 approach...  And not that hard to implement.

**Comment by RubarbKid** [comment]
Sorry, I just realized I left out some of the process...  I didn't mean all 16 files would get "mycat+2.jpg" for a filename.  I meant the 2nd mycat file would get "mycat+2.jpg".  The 3rd would get "mycat+3.jpg" and so on.  The name saved in the map would be the actual saved filename, not the original.   Add a file to the map after a successful download.  The map would only be associated with a single thread and could be kept in the DB (released when the thread is removed), or in a "filename-map.txt" file in the save folder.

**Comment by andyklimczak** [comment]
Good points, I hadn't considered those potential conflicts. I'll close this pr since it has issues. 

I'll submit again if I get inspired with a proper fix.

**Pull request closed without merging**
