### PR TITLE
#362, Filter Watching

### LINKED ISSUE #362: [Feature] Add Filter option to notify you when thread is made matching filter
Not sure if this would really work, since it requires Clover to constantly refresh the catalog. But it'd be nice to be notified when a thread matching your filter is made.

### PR DESCRIPTION
**Pull request by Adamantcheese**
Closes #362

### CODE REVIEW

**Comment by Adamantcheese** [comment]
As a side note, a number of other issues are "resolved" by adding this feature, like #164 or #510,

**Comment by Adamantcheese** [comment]
Also I'm sorry about all the weird commit crap, I messed up with some branches for other features and had to fix it.

**Review by blafaz69 — APPROVED** [review]

**Comment by Adamantcheese** [comment]
I'm going to call this done for now. It works for, at a minimum, one site. Multiple sites may mess it up, it doesn't properly use things that Floens has provided for sure, but it is a good baseline for building off of. A debug build of this can be found at https://github.com/Adamantcheese/Clover/releases along with the other pull requests I put in.

**Comment by Adamantcheese** [comment]
In looking for other things to fix and submit pull requests for, #462 is also "solved" by this.

**Comment by Adamantcheese** [comment]
At this point I'm not going to submit any other pull requests. I think that the 8 I put in are plenty more than enough. [If anyone's reading this, they can find a debug multi-release of all the features from the pulls here.](https://github.com/Adamantcheese/Clover/releases)

**Pull request closed without merging**
