### PR TITLE
Some fixes and cleaning. Added sharing posts.

### PR DESCRIPTION
**Pull request by beschoenen**
I wasn't really sure how to get the thread id in the ThreadManager class, so if you know a better way please change it, because I have the feeling this may be a bit buggy.

### CODE REVIEW

**Comment by Floens** [comment]
Hey Kevin,

I'm currently rewriting a big part of Clover, and I'll cherry pick your comments (or do it manually) when that's done.
Don't wait for me to finish, you can still commit things, I'll just don't merge them immediately.

Also the Loadable.no is the thread id when it is in thread mode :), so no need to add a new field for it.

**Comment by beschoenen** [comment]
Sure, no problem.
And thanks for the tip.

**Comment by beschoenen** [comment]
This new commit adds the functionality to chose if you want to never automatically play webms or on mobile data, wifi or always play them

**Comment by Floens** [comment]
I think I merged/added all of this manually, except for the network type loading, I'll still have to merge that.

**Comment by Floens** [comment]
Added loading images based on network types here https://github.com/Floens/Clover/commit/84bba00ea2689e4e717e6fc373411ca3c54ccfa7
Ready to close, thanks!

**Pull request closed without merging**
