### PR TITLE
#487, Image re encoding

### LINKED ISSUE #487: Support image re-encoding before post (like Dashchan)
As the title says, the Dashchan app allows the user to re-encode the image before posting. It supports:

- Removing Metadata
- Remove File Name
- Re-encode to JPEG and PNG
- Modify quality (0-100%)
- **Reduce size (1-8 times smaller than original)**

Most importantly, I wish the last option was introduced (reduce size), I post pictures taken with my camera on /ic/, and uploading 3000x4500 images is a pain for everyone, and manually reducing the size on android requires a lot of fiddling (installing shady apps etc.)

Thanks

### PR DESCRIPTION
**Pull request by K1rakishou**
Closes #487

Added a new window with lots of options such as remove filename, remove metadata from image, change image checksum, re-encode image to different format (JPEG/PNG) change image quality and scale image down.

55672101-b61e6380-589f-11e9-9b45-9ad8418f5fbb

### CODE REVIEW

**Comment by Adamantcheese** [comment]
It may be worth integrating #653 in with this. I'll take a look and submit a PR on your branch.

**Comment by K1rakishou** [comment]
Yeah, I thought about adding it in this task, but then I saw it already done.

**Comment by Adamantcheese** [comment]
I've submitted a pull request on your 487 branch (https://github.com/K1rakishou/Clover/pull/1), and closed the PR for my EXIF changes (https://github.com/Floens/Clover/pull/653).

**Comment by K1rakishou** [comment]
Done.

**Comment by Adamantcheese** [comment]
Great, really appreciate it. The rest of it looks good, but I'm not a reviewer on the project so I can't say much.

**Comment by Adamantcheese** [comment]
Hey @K1rakishou, just letting you know I've merged your branch into my own multi-feature branch, if you want a build with this feature in it along with a bunch of other stuff I've added as well, [you can find that here.](https://github.com/Adamantcheese/Clover/releases) I'm going to look at your other branches and I might add in the other stuff you've built.

**Comment by K1rakishou** [comment]
@Adamantcheese Yeah, I'm already using your build. Thanks for the merge, btw. You are free to merge my other branches (I would really appreciate it, actually) and if you find some questionable code just notify me I'll fix it.

**Comment by K1rakishou** [comment]
A tiny improvement here. I made these buttons to have the maximum width they can take so it is more convenient to click them (you don't have to reach all the way to the left side)

**Pull request closed without merging**
