### PR TITLE
#647, fix search not reappearing correctly

### LINKED ISSUE #647: Search no longer stays open when leaving a thread in v3.0.2
In version 3.0.1 when searching threads the search results would remain open after backing out of a thread allowing me to continue browsing the results.

In version 3.0.2 backing out of a thread clears the results and clears any text in the search bar. I have to retype my search every time.

In addition tapping search no longer automatically brings up the keyboard. I have to manually tap in the text field to start typing.

### PR DESCRIPTION
**Pull request by Adamantcheese**
Fixes #647, search now closes correctly and retains the last search query. Also the keyboard opens when the search is opened and tapping a post after searching in a thread closes the search window correctly (but doesn't retain the search). Also there's some minor cleanup of some unused stuff and display code duplication.

### CODE REVIEW

**Comment by ghost** [comment]
Your latest version crashes when scrolling to the bottom of a post.

**Comment by Adamantcheese** [comment]
Yeah I just took a look at it. I'm getting it when search is open in a thread and you scroll? It's not happening in any of the code I wrote for this pull, it's happening in an internal view holder check. I'll take a closer look later, but for now just avoid searching in threads. I'll double check to make sure this isn't a problem with the base 3.0.2 or previous versions, because my changes shouldn't have done anything to cause the crash.

For reference, here's the entire error, in case anyone else wants to peruse what might be wrong
```E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.floens.chan, PID: 6157
    java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 85(offset:85).state:500 android.support.v7.widget.RecyclerView{5eadae8 VFED..... .......D 0,0-1080,1731 #7f0900e9 app:id/recycler_view}, adapter:org.floens.chan.ui.adapter.PostAdapter@3c68e4c, layout:org.floens.chan.ui.layout.ThreadListLayout$2@5adee95, context:org.floens.chan.ui.activity.BoardActivity@e1647d
        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5817)
        at android.support.v7.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:285)
        at android.support.v7.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:342)
        at android.support.v7.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:358)
        at android.support.v7.widget.GapWorker.prefetch(GapWorker.java:365)
        at android.support.v7.widget.GapWorker.run(GapWorker.java:396)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by ghost** [comment]
> I'm getting it when search is open in a thread and you scroll?

No, I just open a post scroll to the bottom and it crashes.
In posts with no replies just crashes entering the post.
This is on Android 6 if that matters.

**Comment by Adamantcheese** [comment]
I'm reverting the commit and putting a new build up without it for now while I work it out.

**Comment by ghost** [comment]
Somehow still crashing.

**Comment by Adamantcheese** [comment]
Just this pull alone doesn't seem to crash anything, it's a combination of some of the other stuff I've pulled in. I'm not sure what's causing it.

**Comment by Adamantcheese** [comment]
@myuli I've made a new build without #654 in it, as it was causing the crashing issues. Do be aware that it does downgrade the database and you will have to reinstall and will lose all your settings, saved threads, etc.

**Comment by ghost** [comment]
It works!
Thanks, man. The work you and @K1rakishou are doing is really great.

**Comment by Adamantcheese** [comment]
I've added one more thing to this PR, which is that the arrow menu wasn't toggling correctly. Opening up search on a board would leave the arrow menu as the three lines instead of an arrow, and going into a thread from that state would also leave it as the three lines. The arrow menu drawable is now correctly updated regardless of animation type.

**Pull request closed without merging**
